import { Route, Switch } from 'react-router-dom'
import { useState } from 'react'
import Allison from './Admin/Allison'
import Start from './Act0/Map1'
import Rolled from './Rolled/Rolled'
import TrackA2 from './TrackA/TrackA2'
import Login from './Session/Login'
import SMDesk from './Admin/SMDesk'
import TrackARouter from './TrackA/TrackARouter'
import TrackBRouter from './TrackB/TrackBRouter'
import TrackCRouter from './TrackC/TrackCRouter'
import TrackDRouter from './TrackD/TrackDRouter'
import TrackERouter from './TrackE/TrackERouter'
import { connect } from 'react-redux'
import UserHelp from './Chat/UserHelp'
import { HelpButton, BottomRight } from './Styles/Styles'